dist: xenial

language: python

python:
  - '3.4'
  - '3.5'

env:
  - DB_NAME=raster_test PYTHONPATH=$PYTHONPATH:$PWD DJANGO_SETTINGS_MODULE=tests.testproj.settings

addons:
  postgresql: 9.6
  services:
  - postgresql
  apt:
    packages:
    - postgresql-9.6-postgis-2.4

before_script:
  - psql -U postgres -c 'create extension postgis'
  - psql -c 'create database raster_test' -U postgres

install:
  - pip install -e .
  - pip install psycopg2-binary==2.8.4
  - pip install flake8==3.7.9
  - pip install isort==4.3.21
  - pip install coverage==4.5.4
  - pip install coveralls
  - pip install mock

script: coverage run --include="raster/*" $(which django-admin.py) test

after_success: coveralls

notifications:
  email: false
